/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stellar;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aturn
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
       initComponents();
        staricon();
        setTitle("Stellar: Administrator");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_panel = new javax.swing.JPanel();
        admin_tab = new javax.swing.JTabbedPane();
        addclass_tab = new javax.swing.JPanel();
        addclass_spanel = new javax.swing.JScrollPane();
        classes_table = new javax.swing.JTable();
        classtitle_label = new javax.swing.JLabel();
        classtitle_input = new javax.swing.JTextField();
        classid_label = new javax.swing.JLabel();
        classid_input = new javax.swing.JTextField();
        credit_label = new javax.swing.JLabel();
        credit_input = new javax.swing.JTextField();
        subject_label = new javax.swing.JLabel();
        subject_input = new javax.swing.JTextField();
        addclass_label = new javax.swing.JLabel();
        clearclass_button = new javax.swing.JButton();
        addclass_button = new javax.swing.JButton();
        teachers_tab = new javax.swing.JPanel();
        teacher_spanel = new javax.swing.JScrollPane();
        teachers_table = new javax.swing.JTable();
        addteacher_label = new javax.swing.JLabel();
        fname_label = new javax.swing.JLabel();
        fname_input = new javax.swing.JTextField();
        lname_label = new javax.swing.JLabel();
        lname_input = new javax.swing.JTextField();
        prefix_label = new javax.swing.JLabel();
        prefix_input = new javax.swing.JTextField();
        teacherid_label = new javax.swing.JLabel();
        teacherid_input = new javax.swing.JTextField();
        clearteacher_button = new javax.swing.JButton();
        teacher_button = new javax.swing.JButton();
        students_tab = new javax.swing.JPanel();
        student_spanel = new javax.swing.JScrollPane();
        student_table = new javax.swing.JTable();
        addstudent_label = new javax.swing.JLabel();
        firstname_label = new javax.swing.JLabel();
        firstname_input = new javax.swing.JTextField();
        lastname_label = new javax.swing.JLabel();
        lastname_input = new javax.swing.JTextField();
        studentid_label = new javax.swing.JLabel();
        studentid_input = new javax.swing.JTextField();
        password_label = new javax.swing.JLabel();
        password_input = new javax.swing.JTextField();
        clearstudent_button = new javax.swing.JButton();
        addstudents_button = new javax.swing.JButton();
        stellarnum_label = new javax.swing.JLabel();
        stellarnum_input = new javax.swing.JTextField();
        email_label = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        gpa_label = new javax.swing.JLabel();
        gpa_input = new javax.swing.JTextField();
        major_label = new javax.swing.JLabel();
        major_input = new javax.swing.JTextField();
        year_label = new javax.swing.JLabel();
        year_input = new javax.swing.JTextField();
        bday_label = new javax.swing.JLabel();
        bday_input = new javax.swing.JTextField();
        update_tab = new javax.swing.JPanel();
        update_spanel = new javax.swing.JScrollPane();
        updateclass_table = new javax.swing.JTable();
        updateclass_label = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        classinstructor_tab = new javax.swing.JPanel();
        classinstructor_spanel = new javax.swing.JScrollPane();
        classinstructor_table = new javax.swing.JTable();
        classinstructor_label = new javax.swing.JLabel();
        crn_label = new javax.swing.JLabel();
        crn_input = new javax.swing.JTextField();
        teachid_label = new javax.swing.JLabel();
        teachid_input = new javax.swing.JTextField();
        clasid_label = new javax.swing.JLabel();
        clasid_input = new javax.swing.JTextField();
        semester_label = new javax.swing.JLabel();
        semester_input = new javax.swing.JTextField();
        clearinstructors_button = new javax.swing.JButton();
        addinstructor_button = new javax.swing.JButton();
        days_label = new javax.swing.JLabel();
        days_input = new javax.swing.JTextField();
        classtime_label = new javax.swing.JLabel();
        classtime_input = new javax.swing.JTextField();
        logout_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin_panel.setBackground(new java.awt.Color(204, 204, 204));

        admin_tab.setBackground(new java.awt.Color(255, 215, 73));
        admin_tab.setForeground(new java.awt.Color(51, 51, 51));

        addclass_tab.setBackground(new java.awt.Color(255, 255, 255));
        addclass_tab.setForeground(new java.awt.Color(51, 51, 51));

        classes_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        addclass_spanel.setViewportView(classes_table);

        classtitle_label.setForeground(new java.awt.Color(51, 51, 51));
        classtitle_label.setText("Class Title:");

        classtitle_input.setBackground(new java.awt.Color(255, 255, 255));
        classtitle_input.setForeground(new java.awt.Color(51, 51, 51));
        classtitle_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classtitle_inputActionPerformed(evt);
            }
        });

        classid_label.setForeground(new java.awt.Color(51, 51, 51));
        classid_label.setText("Class ID:");

        classid_input.setBackground(new java.awt.Color(255, 255, 255));
        classid_input.setForeground(new java.awt.Color(51, 51, 51));

        credit_label.setForeground(new java.awt.Color(51, 51, 51));
        credit_label.setText("Credit:");

        credit_input.setBackground(new java.awt.Color(255, 255, 255));
        credit_input.setForeground(new java.awt.Color(51, 51, 51));

        subject_label.setForeground(new java.awt.Color(51, 51, 51));
        subject_label.setText("Subject:");

        subject_input.setBackground(new java.awt.Color(255, 255, 255));
        subject_input.setForeground(new java.awt.Color(51, 51, 51));

        addclass_label.setBackground(new java.awt.Color(102, 102, 102));
        addclass_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addclass_label.setForeground(new java.awt.Color(51, 51, 51));
        addclass_label.setText("Add Class:");

        clearclass_button.setText("Clear");

        addclass_button.setText("Add");

        javax.swing.GroupLayout addclass_tabLayout = new javax.swing.GroupLayout(addclass_tab);
        addclass_tab.setLayout(addclass_tabLayout);
        addclass_tabLayout.setHorizontalGroup(
            addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addclass_tabLayout.createSequentialGroup()
                .addComponent(addclass_spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addclass_tabLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(classtitle_label)
                                .addComponent(classid_label)
                                .addComponent(credit_label)
                                .addComponent(subject_label)
                                .addComponent(classtitle_input)
                                .addComponent(classid_input, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                .addComponent(credit_input)
                                .addComponent(subject_input))
                            .addComponent(addclass_label)))
                    .addGroup(addclass_tabLayout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(clearclass_button)
                        .addGap(30, 30, 30)
                        .addComponent(addclass_button)))
                .addGap(0, 243, Short.MAX_VALUE))
        );
        addclass_tabLayout.setVerticalGroup(
            addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addclass_spanel, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(addclass_tabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(addclass_label)
                .addGap(31, 31, 31)
                .addComponent(classtitle_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classtitle_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(credit_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(credit_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subject_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subject_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(addclass_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearclass_button)
                    .addComponent(addclass_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_tab.addTab("Add Class", addclass_tab);

        teachers_tab.setBackground(new java.awt.Color(255, 255, 255));

        teachers_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        teacher_spanel.setViewportView(teachers_table);

        addteacher_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addteacher_label.setForeground(new java.awt.Color(51, 51, 51));
        addteacher_label.setText("Add Teacher:");

        fname_label.setForeground(new java.awt.Color(51, 51, 51));
        fname_label.setText("First Name:");

        fname_input.setBackground(new java.awt.Color(255, 255, 255));
        fname_input.setForeground(new java.awt.Color(51, 51, 51));
        fname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fname_inputActionPerformed(evt);
            }
        });

        lname_label.setForeground(new java.awt.Color(51, 51, 51));
        lname_label.setText("Last Name:");

        lname_input.setBackground(new java.awt.Color(255, 255, 255));
        lname_input.setForeground(new java.awt.Color(51, 51, 51));

        prefix_label.setForeground(new java.awt.Color(51, 51, 51));
        prefix_label.setText("Prefix:");

        prefix_input.setBackground(new java.awt.Color(255, 255, 255));
        prefix_input.setForeground(new java.awt.Color(51, 51, 51));

        teacherid_label.setForeground(new java.awt.Color(51, 51, 51));
        teacherid_label.setText("ID:");

        teacherid_input.setBackground(new java.awt.Color(255, 255, 255));
        teacherid_input.setForeground(new java.awt.Color(51, 51, 51));

        clearteacher_button.setText("Clear");

        teacher_button.setText("Add");

        javax.swing.GroupLayout teachers_tabLayout = new javax.swing.GroupLayout(teachers_tab);
        teachers_tab.setLayout(teachers_tabLayout);
        teachers_tabLayout.setHorizontalGroup(
            teachers_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(teachers_tabLayout.createSequentialGroup()
                .addComponent(teacher_spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addGroup(teachers_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(teachers_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(fname_label)
                        .addComponent(lname_label)
                        .addComponent(prefix_label)
                        .addComponent(teacherid_label)
                        .addComponent(fname_input)
                        .addComponent(lname_input)
                        .addComponent(prefix_input)
                        .addComponent(teacherid_input, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addteacher_label)
                    .addGroup(teachers_tabLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(clearteacher_button)
                        .addGap(30, 30, 30)
                        .addComponent(teacher_button)))
                .addGap(200, 200, 200))
        );
        teachers_tabLayout.setVerticalGroup(
            teachers_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(teacher_spanel, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(teachers_tabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(addteacher_label)
                .addGap(31, 31, 31)
                .addComponent(fname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(prefix_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prefix_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teacherid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(teachers_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearteacher_button)
                    .addComponent(teacher_button))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_tab.addTab("Teachers", teachers_tab);

        students_tab.setBackground(new java.awt.Color(255, 255, 255));

        student_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        student_spanel.setViewportView(student_table);

        addstudent_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        addstudent_label.setForeground(new java.awt.Color(51, 51, 51));
        addstudent_label.setText("Add Student:");

        firstname_label.setForeground(new java.awt.Color(51, 51, 51));
        firstname_label.setText("First Name:");

        firstname_input.setBackground(new java.awt.Color(255, 255, 255));
        firstname_input.setForeground(new java.awt.Color(51, 51, 51));
        firstname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstname_inputActionPerformed(evt);
            }
        });

        lastname_label.setForeground(new java.awt.Color(51, 51, 51));
        lastname_label.setText("Last Name:");

        lastname_input.setBackground(new java.awt.Color(255, 255, 255));
        lastname_input.setForeground(new java.awt.Color(51, 51, 51));

        studentid_label.setForeground(new java.awt.Color(51, 51, 51));
        studentid_label.setText("ID:");

        studentid_input.setBackground(new java.awt.Color(255, 255, 255));
        studentid_input.setForeground(new java.awt.Color(51, 51, 51));

        password_label.setForeground(new java.awt.Color(51, 51, 51));
        password_label.setText("Password:");

        password_input.setBackground(new java.awt.Color(255, 255, 255));
        password_input.setForeground(new java.awt.Color(51, 51, 51));

        clearstudent_button.setText("Clear");

        addstudents_button.setText("Add");
        addstudents_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addstudents_buttonActionPerformed(evt);
            }
        });

        stellarnum_label.setForeground(new java.awt.Color(51, 51, 51));
        stellarnum_label.setText("Stellar Number:");

        stellarnum_input.setBackground(new java.awt.Color(255, 255, 255));
        stellarnum_input.setForeground(new java.awt.Color(51, 51, 51));
        stellarnum_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stellarnum_inputActionPerformed(evt);
            }
        });

        email_label.setForeground(new java.awt.Color(51, 51, 51));
        email_label.setText("E-mail:");

        email_input.setBackground(new java.awt.Color(255, 255, 255));
        email_input.setForeground(new java.awt.Color(51, 51, 51));

        gpa_label.setForeground(new java.awt.Color(51, 51, 51));
        gpa_label.setText("GPA:");

        gpa_input.setBackground(new java.awt.Color(255, 255, 255));
        gpa_input.setForeground(new java.awt.Color(51, 51, 51));

        major_label.setForeground(new java.awt.Color(51, 51, 51));
        major_label.setText("Major:");

        major_input.setBackground(new java.awt.Color(255, 255, 255));
        major_input.setForeground(new java.awt.Color(51, 51, 51));

        year_label.setForeground(new java.awt.Color(51, 51, 51));
        year_label.setText("School Year:");

        year_input.setBackground(new java.awt.Color(255, 255, 255));
        year_input.setForeground(new java.awt.Color(51, 51, 51));

        bday_label.setForeground(new java.awt.Color(51, 51, 51));
        bday_label.setText("Birthday:");

        bday_input.setBackground(new java.awt.Color(255, 255, 255));
        bday_input.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout students_tabLayout = new javax.swing.GroupLayout(students_tab);
        students_tab.setLayout(students_tabLayout);
        students_tabLayout.setHorizontalGroup(
            students_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(students_tabLayout.createSequentialGroup()
                .addComponent(student_spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(students_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(students_tabLayout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(clearstudent_button)
                        .addGap(30, 30, 30)
                        .addComponent(addstudents_button))
                    .addGroup(students_tabLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(students_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bday_label)
                            .addComponent(year_label)
                            .addComponent(major_label)
                            .addComponent(gpa_label)
                            .addComponent(email_label)
                            .addComponent(firstname_label)
                            .addComponent(lastname_label)
                            .addComponent(studentid_label)
                            .addComponent(password_label)
                            .addComponent(firstname_input)
                            .addComponent(lastname_input)
                            .addComponent(studentid_input)
                            .addComponent(password_input, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(addstudent_label)
                            .addComponent(stellarnum_label)
                            .addComponent(stellarnum_input)
                            .addComponent(email_input)
                            .addComponent(gpa_input)
                            .addComponent(major_input)
                            .addComponent(year_input)
                            .addComponent(bday_input))))
                .addContainerGap())
        );
        students_tabLayout.setVerticalGroup(
            students_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(student_spanel)
            .addGroup(students_tabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(addstudent_label)
                .addGap(31, 31, 31)
                .addComponent(firstname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lastname_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(studentid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stellarnum_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(stellarnum_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(email_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(gpa_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gpa_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(major_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(major_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(year_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(year_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bday_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bday_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(students_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearstudent_button)
                    .addComponent(addstudents_button))
                .addGap(31, 31, 31))
        );

        admin_tab.addTab("Students", students_tab);

        update_tab.setBackground(new java.awt.Color(255, 255, 255));

        updateclass_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        update_spanel.setViewportView(updateclass_table);

        updateclass_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        updateclass_label.setForeground(new java.awt.Color(51, 51, 51));
        updateclass_label.setText("Update Class:");

        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setText("Class Title:");

        jTextField17.setBackground(new java.awt.Color(255, 255, 255));
        jTextField17.setForeground(new java.awt.Color(51, 51, 51));
        jTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField17ActionPerformed(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setText("Class ID:");

        jTextField18.setBackground(new java.awt.Color(255, 255, 255));
        jTextField18.setForeground(new java.awt.Color(51, 51, 51));

        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setText("Credit:");

        jTextField19.setBackground(new java.awt.Color(255, 255, 255));
        jTextField19.setForeground(new java.awt.Color(51, 51, 51));

        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setText("Subject:");

        jTextField20.setBackground(new java.awt.Color(255, 255, 255));
        jTextField20.setForeground(new java.awt.Color(51, 51, 51));

        jButton9.setText("Clear");

        jButton10.setText("Update");

        javax.swing.GroupLayout update_tabLayout = new javax.swing.GroupLayout(update_tab);
        update_tab.setLayout(update_tabLayout);
        update_tabLayout.setHorizontalGroup(
            update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(update_tabLayout.createSequentialGroup()
                .addComponent(update_spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200)
                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel22)
                        .addComponent(jLabel23)
                        .addComponent(jLabel24)
                        .addComponent(jLabel25)
                        .addComponent(jTextField17)
                        .addComponent(jTextField18)
                        .addComponent(jTextField19)
                        .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(updateclass_label)
                    .addGroup(update_tabLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jButton9)
                        .addGap(30, 30, 30)
                        .addComponent(jButton10)))
                .addGap(200, 200, 200))
        );
        update_tabLayout.setVerticalGroup(
            update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(update_spanel, javax.swing.GroupLayout.DEFAULT_SIZE, 771, Short.MAX_VALUE)
            .addGroup(update_tabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(updateclass_label)
                .addGap(31, 31, 31)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(update_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_tab.addTab("Update Class", update_tab);

        classinstructor_tab.setBackground(new java.awt.Color(255, 255, 255));

        classinstructor_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        classinstructor_spanel.setViewportView(classinstructor_table);

        classinstructor_label.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        classinstructor_label.setForeground(new java.awt.Color(51, 51, 51));
        classinstructor_label.setText("Class Instructors:");

        crn_label.setForeground(new java.awt.Color(51, 51, 51));
        crn_label.setText("CRN:");

        crn_input.setBackground(new java.awt.Color(255, 255, 255));
        crn_input.setForeground(new java.awt.Color(51, 51, 51));
        crn_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crn_inputActionPerformed(evt);
            }
        });

        teachid_label.setForeground(new java.awt.Color(51, 51, 51));
        teachid_label.setText("Teacher ID:");

        teachid_input.setBackground(new java.awt.Color(255, 255, 255));
        teachid_input.setForeground(new java.awt.Color(51, 51, 51));

        clasid_label.setForeground(new java.awt.Color(51, 51, 51));
        clasid_label.setText("Class ID:");

        clasid_input.setBackground(new java.awt.Color(255, 255, 255));
        clasid_input.setForeground(new java.awt.Color(51, 51, 51));

        semester_label.setForeground(new java.awt.Color(51, 51, 51));
        semester_label.setText("Semester:");

        semester_input.setBackground(new java.awt.Color(255, 255, 255));
        semester_input.setForeground(new java.awt.Color(51, 51, 51));

        clearinstructors_button.setText("Clear");

        addinstructor_button.setText("Add");

        days_label.setForeground(new java.awt.Color(51, 51, 51));
        days_label.setText("Days:");

        days_input.setBackground(new java.awt.Color(255, 255, 255));
        days_input.setForeground(new java.awt.Color(51, 51, 51));

        classtime_label.setForeground(new java.awt.Color(51, 51, 51));
        classtime_label.setText("Class Time:");

        classtime_input.setBackground(new java.awt.Color(255, 255, 255));
        classtime_input.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout classinstructor_tabLayout = new javax.swing.GroupLayout(classinstructor_tab);
        classinstructor_tab.setLayout(classinstructor_tabLayout);
        classinstructor_tabLayout.setHorizontalGroup(
            classinstructor_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classinstructor_tabLayout.createSequentialGroup()
                .addComponent(classinstructor_spanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(classinstructor_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classinstructor_tabLayout.createSequentialGroup()
                        .addGap(336, 336, 336)
                        .addComponent(clearinstructors_button)
                        .addGap(30, 30, 30)
                        .addComponent(addinstructor_button))
                    .addGroup(classinstructor_tabLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(classinstructor_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(classtime_label)
                            .addComponent(crn_label)
                            .addComponent(teachid_label)
                            .addComponent(clasid_label)
                            .addComponent(semester_label)
                            .addComponent(crn_input)
                            .addComponent(teachid_input)
                            .addComponent(clasid_input)
                            .addComponent(semester_input, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                            .addComponent(classinstructor_label)
                            .addComponent(days_label)
                            .addComponent(days_input)
                            .addComponent(classtime_input))))
                .addContainerGap())
        );
        classinstructor_tabLayout.setVerticalGroup(
            classinstructor_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classinstructor_spanel)
            .addGroup(classinstructor_tabLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(classinstructor_label)
                .addGap(31, 31, 31)
                .addComponent(crn_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crn_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(teachid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teachid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clasid_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clasid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semester_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(semester_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(days_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(days_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(classtime_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classtime_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(classinstructor_tabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearinstructors_button)
                    .addComponent(addinstructor_button))
                .addContainerGap(284, Short.MAX_VALUE))
        );

        admin_tab.addTab("Class Instructors", classinstructor_tab);

        logout_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stellar/door12.png"))); // NOI18N
        logout_button.setText("Logout");
        logout_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_buttonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout admin_panelLayout = new javax.swing.GroupLayout(admin_panel);
        admin_panel.setLayout(admin_panelLayout);
        admin_panelLayout.setHorizontalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_tab, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logout_button)
                .addGap(17, 17, 17))
        );
        admin_panelLayout.setVerticalGroup(
            admin_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, admin_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logout_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(admin_tab, javax.swing.GroupLayout.PREFERRED_SIZE, 797, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(admin_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 841, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_buttonMouseClicked
       int logout_con = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);

        if (logout_con == 0){
            Login log = new Login();
            log.setVisible(true);
            log.pack();
            log.setLocationRelativeTo(null);
            log.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            dispose();

        }
    }//GEN-LAST:event_logout_buttonMouseClicked

    private void classtitle_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classtitle_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_classtitle_inputActionPerformed

    private void fname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fname_inputActionPerformed

    private void firstname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstname_inputActionPerformed

    private void crn_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crn_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crn_inputActionPerformed

    private void jTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField17ActionPerformed

    private void addstudents_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addstudents_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addstudents_buttonActionPerformed

    private void stellarnum_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stellarnum_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stellarnum_inputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }
    
      public void staricon(){
    setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("star-icon.png")));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addclass_button;
    private javax.swing.JLabel addclass_label;
    private javax.swing.JScrollPane addclass_spanel;
    private javax.swing.JPanel addclass_tab;
    private javax.swing.JButton addinstructor_button;
    private javax.swing.JLabel addstudent_label;
    private javax.swing.JButton addstudents_button;
    private javax.swing.JLabel addteacher_label;
    private javax.swing.JPanel admin_panel;
    private javax.swing.JTabbedPane admin_tab;
    private javax.swing.JTextField bday_input;
    private javax.swing.JLabel bday_label;
    private javax.swing.JTextField clasid_input;
    private javax.swing.JLabel clasid_label;
    private javax.swing.JTable classes_table;
    private javax.swing.JTextField classid_input;
    private javax.swing.JLabel classid_label;
    private javax.swing.JLabel classinstructor_label;
    private javax.swing.JScrollPane classinstructor_spanel;
    private javax.swing.JPanel classinstructor_tab;
    private javax.swing.JTable classinstructor_table;
    private javax.swing.JTextField classtime_input;
    private javax.swing.JLabel classtime_label;
    private javax.swing.JTextField classtitle_input;
    private javax.swing.JLabel classtitle_label;
    private javax.swing.JButton clearclass_button;
    private javax.swing.JButton clearinstructors_button;
    private javax.swing.JButton clearstudent_button;
    private javax.swing.JButton clearteacher_button;
    private javax.swing.JTextField credit_input;
    private javax.swing.JLabel credit_label;
    private javax.swing.JTextField crn_input;
    private javax.swing.JLabel crn_label;
    private javax.swing.JTextField days_input;
    private javax.swing.JLabel days_label;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel email_label;
    private javax.swing.JTextField firstname_input;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JTextField fname_input;
    private javax.swing.JLabel fname_label;
    private javax.swing.JTextField gpa_input;
    private javax.swing.JLabel gpa_label;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField lastname_input;
    private javax.swing.JLabel lastname_label;
    private javax.swing.JTextField lname_input;
    private javax.swing.JLabel lname_label;
    private javax.swing.JButton logout_button;
    private javax.swing.JTextField major_input;
    private javax.swing.JLabel major_label;
    private javax.swing.JTextField password_input;
    private javax.swing.JLabel password_label;
    private javax.swing.JTextField prefix_input;
    private javax.swing.JLabel prefix_label;
    private javax.swing.JTextField semester_input;
    private javax.swing.JLabel semester_label;
    private javax.swing.JTextField stellarnum_input;
    private javax.swing.JLabel stellarnum_label;
    private javax.swing.JScrollPane student_spanel;
    private javax.swing.JTable student_table;
    private javax.swing.JTextField studentid_input;
    private javax.swing.JLabel studentid_label;
    private javax.swing.JPanel students_tab;
    private javax.swing.JTextField subject_input;
    private javax.swing.JLabel subject_label;
    private javax.swing.JButton teacher_button;
    private javax.swing.JScrollPane teacher_spanel;
    private javax.swing.JTextField teacherid_input;
    private javax.swing.JLabel teacherid_label;
    private javax.swing.JPanel teachers_tab;
    private javax.swing.JTable teachers_table;
    private javax.swing.JTextField teachid_input;
    private javax.swing.JLabel teachid_label;
    private javax.swing.JScrollPane update_spanel;
    private javax.swing.JPanel update_tab;
    private javax.swing.JLabel updateclass_label;
    private javax.swing.JTable updateclass_table;
    private javax.swing.JTextField year_input;
    private javax.swing.JLabel year_label;
    // End of variables declaration//GEN-END:variables
}
